apiVersion: apps/v1
kind: Deployment
metadata:
  name: perepiski
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perepiski
  template:
    metadata:
      labels:
        app: perepiski
    spec:
      containers:
        - name: perepiski
          image: ghcr.io/hismaj3sty/fewd-svelte
