apiVersion: v1
kind: Service
metadata:
  name: perepiski
  namespace: default
spec:
  ports:
    - name: front  
      port: 8080
      targetPort: 80
      protocol: TCP
    - name: back
      port: 8081
      targetPort: 81
      protocol: TCP
  selector:
    app: perepiski
